#!/usr/bin/env php
<?php

ini_set('memory_limit', '512m');
include(__DIR__ . '/GeoJSON2Image.php');
$json = json_decode(file_Get_Contents($_SERVER['argv'][1]));
$json2image = new GeoJSON2Image($json);
$json2image->setSize(1000);
$ret = $json2image->json2image($json);
imagepng($ret['image'], 'output.png');
print_r($ret['boundry']);
